options(repos="http://cran.rstudio.com/")
Sys.setenv("RENV_CONFIG_REPOS_OVERRIDE" = "http://cran.rstudio.com")

library(here)
library(wbstats)
library(tidyverse)

countries <- wbstats::wb_countries() %>%
  filter(region!="Aggregates") %>%
  select(country, iso2c, region, income_level) 

# Convert the dataframe to a list of lists
countries <- split(countries, 1:nrow(countries))

countries <- sample(countries, 25)

year <- 2022
# Loop through the list of countries and generate .qmd files
for (country_info in countries) {
  # Extract country-specific information
  country <- country_info$country
  iso2c <- country_info$iso2c
  region <- country_info$region
  income_level <- country_info$income_level
  
  # Create the content for the .qmd file
  content <- paste0(
    '---\n',
    sprintf('title: "%s"\n', country),
    'format:\n',
    '    html:\n',
    '        embed-resources: true\n',
    'subtitle: "SPI Country Brief"\n',
    'description: |\n',
    sprintf('  This SPI country report is designed to give an overview of the performance of %s.\n', country),
    'categories:\n',
    '    - Statistical Performance\n',
    sprintf('    - %s\n', region),
    sprintf('    - %s\n', income_level),
    sprintf('image: images/%s.png\n', iso2c),
    'execute:\n',
    '    echo: false\n',
    '    warning: false\n',
    '---\n\n',
    'The Statistical Performance Indicators measure the capacity and maturity of national statistical systems by assessing the use of data, the quality of services, the coverage of topics, the sources of information, and the infrastructure and availability of resources. The goal is to improve development outcomes and track progress toward the Sustainable Development Goals. \n\n',
    'The hope is that the SPI framework will give countries incentives to build better statistical systems and will help create data ecosystems that can develop and adapt to the requirements of governments and citizens - so that better data can support better decisions.\n\n',
    sprintf('This is the Country Report for **%s** based on data from **%d**.\n\n', country, year),
    '```{r}\nlibrary(tidyverse)\nlibrary(here)\nlibrary(downloadthis)\n```\n\n',
    '{{< downloadthis files/SPI_data.xlsx dname=SPI_Index label="Download the SPI data" icon=database-fill-down type=info class=data-button id=spi >}}\n\n',
    '```{r} \nsource("C:/Users/wb469649/Documents/GitHub/SPI_country_pages/scripts/country_reports_visuals.R")\n``` \n\n',
    sprintf('```{r}\ncntry<- "%s" \nyear <-%d\n```\n\n', country, year),

    # Add the highcharter HTML code to embed the chart
    '```{r} \n
    country_report_lolli_fn("SPI.INDEX", "SPI Overall Scores",100, cntry, yr)\n```\n\n',
    '::: {.column-margin} \n\n The **SPI overall score** is based on five pillars of statistical performance: **data use**, **data services**, **data products**, **data sources**, and **data infrastructure**.  The scores for each pillar are shown in the table. \n\n::: \n\n',
    '```{r} \n
    country_report_lolli_fn("SPI.D1", "Pillar 1: Data Use",1, cntry, yr)\n```\n\n',
    '::: {.column-margin} \n\n **Data Use**: Statistics have value only if they are used. A successful statistical system produces data that are used widely and frequently. \n\n:::\n\n',
    '```{r} \n
    country_report_lolli_fn("SPI.D2", "Pillar 2: Data Services",1, cntry, yr)\n```\n\n',
    '::: {.column-margin} \n\n **Data Services**:  A range of services connects data users to producers and facilitate dialogues between them, thus building trust and adding value to data.. \n\n:::\n\n',
    '```{r} \n
    country_report_lolli_fn("SPI.D3", "Pillar 3: Data Products",1, cntry, yr)\n```\n\n',    
    '::: {.column-margin} \n\n **Data Products**:  The feedback systems between data producers and data users drive the design and help increase the range of statistical products available, and can help improve their accuracy, timeliness, frequency, comparability, and levels of disaggregation. The availability and quality of key NSS data products signal whether countries can produce indicators needed to measure progress toward the 17 Sustainable Development Goals. \n\n::: \n\n',
    '```{r} \n
    country_report_lolli_fn("SPI.D4", "Pillar 4: Data Sources",1, cntry, yr)\n```\n\n',
    '::: {.column-margin} \n\n **Data Sources**:  To create useful products, a statistical system needs to draw on sources inside and outside the government. Modern data collection thus goes beyond the typical censuses and surveys to include administrative and geospatial data, as well as data generated by private firms and citizens. \n\n::: \n\n',
    '```{r} \n
    country_report_lolli_fn("SPI.D5", "Pillar 5: Data Infrastructure",1, cntry, yr)\n```\n\n',
    '::: {.column-margin} \n\n **Data Infrastructure**:  A mature statistical system has well-developed institutional infrastructure (legislation, governance, standards), soft infrastructure (skills, partnerships), and the financial resources to deliver useful—and widely used—data products and services. \n\n::: \n\n',
    'Underpinning these five pillars are 22 dimensions and 51 indicators. Please visit the [framework page](https://www.worldbank.org/en/programs/statistical-performance-indicators/Framework) of the SPI website for more details or read our peer reviewed [journal article](https://www.nature.com/articles/s41597-023-01971-0).'
  )
  
  # Define the filename for the .qmd file
  filename <- here("country_reports","reports",paste0(country, ".qmd"))
  
  # Write the content to the .qmd file
  writeLines(content, filename)
  
  # Print a message indicating the file has been created
  cat(sprintf('Created file: %s\n', filename))
}
